### ISSUE TITLE
Python Okex websocket - return invalid bytes that jason can't decode.

### ISSUE THREAD

**Issue by qianyk369** [OKCoin/websocket#27]
Starting from today, websocket api returns following value when I subscribe to "ok_sub_futureusd_btc_depth_this_week_10"channel:

b'M\xca1\n\x800\x0c\x05\xd0\xbb\xfc\xd9A\xd7\xae\x1eC$\xa4&\xa2(U\xda\x04\x15\xf1\xee.\x0e\x8e\x0f^w#\xce\x89\xf3\x85\xd0T\x18&NIW\x04\xb0H\xfb\xa1\x82\xb01\xc2\x8d\xac\xc5WC\xb0\xec\xfa\xcf\xdbB\xc5#\x8dn\x9e\xd5\x8bP\xb4\x81Dw\x9b(\xe9it\xa8.\xd4\xd4x\x9e\xfe\x05'
2018-10-29 23:01:16,578 - root - ERROR - Expecting value: line 1 column 1 (char 0)

Jason.loads() can't decode it.  Anyone has similar issue or knows what's going on?

Thanks,

**Comment by Chan2008** [comment]
I have the same issue.  I believe they are compressing the data.  Try decompressing with zlib

**Comment by qianyk369** [comment]
@Chan2008 Have you figured out a solution for this issue? Thanks

**Comment by Chan2008** [comment]
Oh... OKEX provided sample code to decompress the data here:  
https://github.com/okcoin-okex/API-docs-OKEx.com/tree/master/demo

**Comment by qianyk369** [comment]
Thanks @Chan2008

**Comment by Chan2008** [comment]
The okcoin api's are more than 4 years old and are probably not supported
anymore.

Check out the new okx api:
https://www.okx.com/docs-v5/en/#market-maker-program
