### ISSUE TITLE
Getting Channel subscription temporally not available on Spot Price API

### ISSUE THREAD

**Issue by jhnferraris** [OKCoin/websocket#7]
I tried the sample code (updated the uri and the keys) and when I execute each Spot Price APIs. The response is "Channel temporary not available"

I'm attaching an image of the logs

![screen shot 2016-09-30 at 4 48 36 pm](https://cloud.githubusercontent.com/assets/3207153/18986440/5a361cb4-872f-11e6-8b72-7d2278121d56.jpg)

Is the websocket down or something?

**Comment by jhnferraris** [comment]
My bad. I missed the changing the values of X and Y

**Comment by HaleyHu** [comment]
Is it work now?
